[theme]
base = "light"
primaryColor = "#171717"
backgroundColor = "#F9F9F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true

[browser]
gatherUsageStats = false
